<div class="menu">
<ul>
	<li><a href="Default.asp" >Home</a></li>
	<li><a href="#" id="current">Add</a>
		<ul>
			<li><a href="AddAccount.asp">Add Account</a></li>
			<li><a href="AddCity.asp">Add City</a></li>
			<li><a href="AddClaim.asp">Add Claim</a></li>
			<li><a href="AddExpenseType.asp">Add Expense Type</a></li>
			<li><a href="AddInvoice.asp">Add Invoice</a></li>
			<li><a href="AddMedication.asp">Add Medication</a></li>
			<li><a href="AddPatient.asp">Add Patient</a></li>
			<li><a href="AddPayee.asp">Add Payee</a></li>
			<li><a href="AddProvider.asp">Add Provider</a></li>
			<li><a href="AddService.asp">Add Service</a></li>
			<li><a href="AddState.asp">Add State</a></li>
		</ul>
	</li>
	<li><a href="#" id="current">Search</a>
		<ul>
			<li><a href="ClaimsSearch.asp">Claims</a></li>
			<li><a href="ClaimAmountsView.asp">Claim Amounts</a></li>
			<li><a href="ClaimsViewByClaimNumber.asp">Claims by Claim Number</a></li>
			<li><a href="ClaimsViewByInsuranceClaimNumber.asp">Claims by Insurnace Number</a></li>
			<li><a href="ClaimsViewByPatientID.asp">Claims by Patient</a></li>
			<li><a href="ClaimsViewByProviderID.asp">Claims by Provider</a></li>
			<li><a href="ClaimsViewByServiceIDAndDate.asp">Claims by Service</a></li>
			<li><a href="ClaimsByMonth.asp">Claims by Month</a></li>
			<!--
			<li><a href="PaidClaimsView.asp">Paid Claims</a></li>
			<li><a href="UnpaidClaimsView.asp">Unpaid Claims</a></li>
			-->
			<li><hr></li>
			<li><a href="InvoicesSearch.asp">Invoices</a></li>
			
		</ul>
	</li>
	<li><a href="#" id="current">View</a>
		<ul>
			<li><a href="AccountsView.asp">Accounts</a></li>
			<li><a href="CitiesView.asp">Cities</a></li>
			<li><a href="ExpenseTypesView.asp">Expense Types</a></li>
			<li><a href="FlexPayRequestAmountsByInsuranceClaimNumberView.asp">Flex Pay Request Amounts</a></li>			
			<li><a href="InvoiceAmountsToPayView.asp">Invoice Amounts To Pay</a></li>
			<!--<li><a href="InvoicesView.asp">Invoices</a></li>-->
			<li><a href="MedicationsView.asp">Medications</a></li>
			<li><a href="PatientsView.asp">Patients</a></li>
			<li><a href="PayeesView.asp">Payees</a></li>
			<li><a href="ProvidersView.asp">Providers</a></li>
			<li><a href="ServicesView.asp">Services</a></li>
			<li><a href="StatesView.asp">States</a></li>
		</ul>
	</li>
	<li><a href="#">Contact</a></li>
</ul>
</div>
